const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=3',
  'https://sanand0.github.io/tdsdata/js_table/?seed=4',
  'https://sanand0.github.io/tdsdata/js_table/?seed=5',
  'https://sanand0.github.io/tdsdata/js_table/?seed=6',
  'https://sanand0.github.io/tdsdata/js_table/?seed=7',
  'https://sanand0.github.io/tdsdata/js_table/?seed=8',
  'https://sanand0.github.io/tdsdata/js_table/?seed=9',
  'https://sanand0.github.io/tdsdata/js_table/?seed=10',
  'https://sanand0.github.io/tdsdata/js_table/?seed=11',
  'https://sanand0.github.io/tdsdata/js_table/?seed=12',
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url, { waitUntil: 'networkidle' });

    // Wait for the table to appear (it's dynamically generated by JS)
    await page.waitForSelector('table');

    // Extract all text inside <td> cells, parse as numbers, and sum them
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('td');
      let sum = 0;
      cells.forEach(cell => {
        const val = parseFloat(cell.innerText.trim());
        if (!isNaN(val)) sum += val;
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Grand Total: ${grandTotal}`);
  await browser.close();
})();
